apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: flux2
spec:
  forProvider:
    chart:
      name: flux2
      repository: https://fluxcd-community.github.io/helm-charts
      version: "2.17.2"
    namespace: fluxcd
    skipCreateNamespace: true
    values:
      helmController:
        create: true
      imageAutomationController:
        create: true
  providerConfigRef:
    name: helm-provider
