apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crossplane-provider/crossplane-ingress-rbac.yml
  - crossplane-provider/crossplane-namespace-rbac.yml
  - crossplane-provider/provider.yaml
  - crossplane-provider/providerconfig.yaml
  - helm/helm-config.yaml
  - helm/helm_rbac.yaml
  - helm/provider_helm.yaml
